name: Hello world workflow
on: 
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down   
      - run: |
          ci/build-app.sh

      - uses: actions/checkout@v4
   
