name: Hello world workflow
on: 
  push:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - name: Clone-down
      - uses: actions/checkout@v4

      - name: List files in the repository
        run: ci/build-app.sh
